version: '3.8'
services:
  tips-api:
    container_name: tips-api
    image: tips-api:${VERSION}
    build:
      context: .
      dockerfile: TipsAPI/Dockerfile
    ports:
      - "${TIPS_API_HTTP_PORT}:5000"
      - "${TIPS_API_HTTPS_PORT}:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    depends_on:
      - tips-db

  tips-db:
    container_name: tips-db
    image: postgres:latest
    environment:
      POSTGRES_DB: sample-tips-api-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  reporting-api:
    container_name: reporting-api
    image: reporting-api:${VERSION}
    build:
      context: .
      dockerfile: ReportingAPI/Dockerfile
    ports:
      - "${REPORTING_API_HTTP_PORT}:6000"
      - "${REPORTING_API_HTTPS_PORT}:6001"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    depends_on:
      - reporting-db
 
  reporting-db:
    container_name: reporting-db
    image: postgres:latest
    environment:
      POSTGRES_DB: sample-reporting-api-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6432:5432"
 
  tips-mq:
      image: rabbitmq:management
      container_name: rabbit-mq
      hostname: tipsmq
      volumes:
        - ./.containers/queue/data/:/var/lib/rabbitmq/mnesia
        - ./.containers/queue/log/:/var/lib/rabbitmq/mnesia
      environment:
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}